/**
 * Security Rule Test Specification for ArchCAD Cloud Persistence
 * Verifies that the "Dirty Dozen" violation payloads are strictly rejected by security rules.
 */

export const DIRTY_DOZEN_TESTS = [
  {
    name: 'Unauthenticated Read',
    auth: null,
    operation: 'get',
    path: '/users/user123/projects/proj1',
    expected: 'PERMISSION_DENIED',
  },
  {
    name: 'Cross-User Snooping',
    auth: { uid: 'user_attacker' },
    operation: 'get',
    path: '/users/user_victim/projects/proj1',
    expected: 'PERMISSION_DENIED',
  },
  {
    name: 'Cross-User Write',
    auth: { uid: 'user_attacker' },
    operation: 'create',
    path: '/users/user_victim/projects/proj1',
    payload: { id: 'proj1', userId: 'user_victim', title: 'Malicious', objectCount: 0, objects: [], updatedAt: 'now', createdAt: 'now' },
    expected: 'PERMISSION_DENIED',
  },
  {
    name: 'Mismatched Path UID',
    auth: { uid: 'user_1' },
    operation: 'create',
    path: '/users/user_1/projects/proj1',
    payload: { id: 'proj1', userId: 'user_2', title: 'Mismatched', objectCount: 0, objects: [], updatedAt: 'now', createdAt: 'now' },
    expected: 'PERMISSION_DENIED',
  },
  {
    name: 'Mismatched Doc ID',
    auth: { uid: 'user_1' },
    operation: 'create',
    path: '/users/user_1/projects/proj1',
    payload: { id: 'proj2', userId: 'user_1', title: 'Mismatched Doc ID', objectCount: 0, objects: [], updatedAt: 'now', createdAt: 'now' },
    expected: 'PERMISSION_DENIED',
  },
  {
    name: 'Path Traversal / Malicious ID',
    auth: { uid: 'user_1' },
    operation: 'create',
    path: '/users/user_1/projects/invalid@bad$id',
    payload: { id: 'invalid@bad$id', userId: 'user_1', title: 'Bad ID', objectCount: 0, objects: [], updatedAt: 'now', createdAt: 'now' },
    expected: 'PERMISSION_DENIED',
  },
  {
    name: 'Giant Title Overflow (>120 chars)',
    auth: { uid: 'user_1' },
    operation: 'create',
    path: '/users/user_1/projects/proj1',
    payload: { id: 'proj1', userId: 'user_1', title: 'A'.repeat(121), objectCount: 0, objects: [], updatedAt: 'now', createdAt: 'now' },
    expected: 'PERMISSION_DENIED',
  },
  {
    name: 'Non-Number Object Count',
    auth: { uid: 'user_1' },
    operation: 'create',
    path: '/users/user_1/projects/proj1',
    payload: { id: 'proj1', userId: 'user_1', title: 'Test', objectCount: 'invalid_number', objects: [], updatedAt: 'now', createdAt: 'now' },
    expected: 'PERMISSION_DENIED',
  },
  {
    name: 'Unbounded Object Flooding (>500 items)',
    auth: { uid: 'user_1' },
    operation: 'create',
    path: '/users/user_1/projects/proj1',
    payload: { id: 'proj1', userId: 'user_1', title: 'Flooded', objectCount: 501, objects: new Array(501).fill({}), updatedAt: 'now', createdAt: 'now' },
    expected: 'PERMISSION_DENIED',
  },
  {
    name: 'Owner Hijack on Update',
    auth: { uid: 'user_1' },
    operation: 'update',
    path: '/users/user_1/projects/proj1',
    payload: { id: 'proj1', userId: 'user_attacker', title: 'Hijacked', objectCount: 0, objects: [], updatedAt: 'now', createdAt: 'now' },
    expected: 'PERMISSION_DENIED',
  },
  {
    name: 'Tampered CreatedAt Timestamp',
    auth: { uid: 'user_1' },
    operation: 'update',
    path: '/users/user_1/projects/proj1',
    payload: { id: 'proj1', userId: 'user_1', title: 'Modified', objectCount: 0, objects: [], updatedAt: 'now', createdAt: 'tampered_date' },
    expected: 'PERMISSION_DENIED',
  },
  {
    name: 'Missing Required Fields',
    auth: { uid: 'user_1' },
    operation: 'create',
    path: '/users/user_1/projects/proj1',
    payload: { id: 'proj1', userId: 'user_1', title: 'Incomplete' },
    expected: 'PERMISSION_DENIED',
  },
];
